language: python
python:
  - 3.5.0
  - 3.5.2
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - 3.7
  - 3.7-dev
  - nightly
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - coverage run --source=dhcpkit setup.py test
after_success:
  - coveralls
